### ISSUE TITLE
statsd as a logstash codec

### ISSUE THREAD

**Issue by regulatre** [statsd/statsd#589]
Feature request - it would be awesome to see the statsd daemon be written as a logstash codec. 

With a codec it could be built right into logstash without the need for separate stand-alone service.  This further lends itself well to scaling and fault tolerant deployments where Kafka is used to deliver data to multiple datacenters for data redundancy

**Comment by mrtazz** [comment]
Presumably this is about writing an input plugin for logstash (https://www.elastic.co/guide/en/logstash/current/input-new-plugin.html). This is not currently in scope for statsd itself, so I'm closing this. Thank you for submitting this suggestion.
