### ISSUE TITLE
Node 7 Tag and NPM Push Needed

### ISSUE THREAD

**Issue by jnovack** [statsd/statsd#613]
A tag for Node 7 and a push up to NPM is needed.

Right now, I cannot get from NPM a working version of statsd for node7.

**Comment by msimerson** [comment]
Agreed. A new release is needed so that distros that install node 7 by default are supported.

**Comment by jackpopp** [comment]
Would great if a new version was tagged and released as currently we cannot use statsd with node 7 or 8. There are a few other comments mentioning this here https://github.com/etsy/statsd/pull/593

**Comment by BlueHatbRit** [comment]
Done, we now support up to node 12 😄 sorry this took so long, the project is now being revived!
