### ISSUE TITLE
admin interface shows graphite.last_exception == uptime, always

### ISSUE THREAD

**Issue by cognitiaclaeves** [statsd/statsd#626]
Another way to say this is that the graphite.last_exception stat is constantly climbing.

What does this mean? How do I fix it?

Also, even though I'm at log > level: LOG_DEBUG, and debug: true, I don't see any log lines in stdout that even indicate there is an exception of any kind happening.

My config:

graphiteHost: carbon
graphitePort: 2003
port: 8125
debug: true
log > level: LOG_DEBUG
flushInterval: 10000
deleteIdleStats: false
deleteCounters: false
deleteTimers: false
deleteSets: false
deleteGauges: false

My stats:

uptime: 2415
messages.last_msg_seen: 2415
messages.bad_lines_seen: 0
graphite.last_flush: 5
graphite.last_exception: 2415
graphite.flush_time: 0
graphite.flush_length: 679

I'm able to graph these in grafana.

Statsd, carbon, graphite-api (not graphite-web), and grafana are all in separate containers.

'carbon' resolves inside the statsd container.

**Comment by cognitiaclaeves** [comment]
I now see this in our main production instance (everything installed to a single server) as well.

I would really appreciate someone's interpretation of what this means.

Is this just a bug in statsd?

**Comment by benburry** [comment]
To establish whether you're able to talk from statsd to graphite:

- Are you seeing statsd metrics in graphite?
- Can you feed data to graphite manually from where statsd is running (something like ```
echo "local.random.diceroll 4 `date +%s`" | nc -q0 <graphiteHost> <graphitePort>```)

**Comment by cognitiaclaeves** [comment]
I am seeing the data in graphite.

What I'm unsure of is why statsd is reporting constant exceptions, and how to determine if there is some kind of issue with the communication that somehow does not appear to affect some data from being shown ...

**Comment by BlueHatbRit** [comment]
This should be fixed with the merging of #707
