### ISSUE TITLE
statsd doesnt work correctly on node version 8+

### ISSUE THREAD

**Issue by DexterHaslem** [statsd/statsd#633]
Running statsd on a modern nodejs version will have some very confusing abnormalities and not work correctly, however it will not throw errors and will mostly silently fail which was brutal. In particular I saw the following:

- `debugMessages` config setting had no effect (!)
- log had no errors
- incoming stats were intermittently not being aggregated and sent out

I'm mostly opening this issue to raise awareness of the nature of the issue so others do not waste time on the mysterious behavior.

Related to #618 I understand this repo has sinked in activity. We could start investigating upgrading to latest and spiffying up the repo if there is enough interest

**Comment by atodd** [comment]
I've added a pull request to address this issue https://github.com/etsy/statsd/pull/637.  It passes all tests on node version 6-9.

**Comment by DexterHaslem** [comment]
awesome, thank you for tackling this

**Comment by q2dg** [comment]
Guys, this project is dead. Let's go to another

**Comment by acanimal** [comment]
Any other alternative projects for node?

**Comment by LarsFronius** [comment]
It appears as of https://github.com/statsd/statsd/commit/ff308f672f598ed22d786e63206d785ed14bb0fc#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 we are testing against node 8+.

Does this mean the issue has been resolved and we can be certain to run on updated versions of node.js?

**Comment by BlueHatbRit** [comment]
Sorry this went on for such a dreadfully long time, the projects just being revived now really. We now support a bunch of LTS versions including node 8, 10, and 12. 8 will be aged off as the nodejs LTS period comes to an end.

Happy statsding!
