### ISSUE TITLE
AttributeError: module 'statsd' has no attribute 'StatsClient'

### ISSUE THREAD

**Issue by resgef** [statsd/statsd#640]
checking statsd(version 3.2.1) usage with 
`import statsd

statsclient = statsd.StatsClient(prefix='asrivr')`

running this script shows error: 
Traceback (most recent call last):
  File "tests/statsd.py", line 14, in <module>
    import statsd
  File "/home/droid/works/python/asrivr/tests/statsd.py", line 16, in <module>
    statsclient = statsd.StatsClient(prefix='asrivr')
AttributeError: module 'statsd' has no attribute 'StatsClient'

**Comment by atomlab** [comment]
I have same error.
```
# pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
```
```
# pip3 list| grep stats
statsd (3.3.0)
```
```
~# python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import statsd
>>> c = statsd.StatsClient('localhost', 8125)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'statsd' has no attribute 'StatsClient'
```
help is empty 
```
>>> help(statsd)
```
output
```
Help on package statsd:

NAME
    statsd

PACKAGE CONTENTS
    client (package)

FILE
    (built-in)

(END)
```

**Comment by BlueHatbRit** [comment]
This looks like it's related to a python client for statsd, this is the statsd daemon itself and not a python project/module.

I'm assuming since it's been so long you've all found the answer and/or moved on from the issue so I'm closing this but feel free to comment again if I've missed something.

**Comment by LFED-FP** [comment]
Getting this problem as well for zero reason

**Comment by BlueHatbRit** [comment]
@yangboz as mentioned further up, this is a problem with the python package you're using. The python package is not maintained by us, you'll need to find that projects repo and reach out to them instead.
