### ISSUE TITLE
OpenCensus backend

### ISSUE THREAD

**Issue by DazWilkin** [statsd/statsd#656]
Hacking around, I've begun working on an [OpenCensus](opencensus.io) backend for statsd:

https://github.com/DazWilkin/statsd-opencensus-backend

It works, basically. I wrote it up [here](https://medium.com/google-cloud/statsd-opencensus-backend-33297c6a58b5) (and in the [README](https://github.com/DazWilkin/statsd-opencensus-backend/blob/master/README.md))

Counters and Gauges are basic but included. Timers are not.

I've yet to grok how to deal with namespaces and tags.

There's a bunch of other functionality that's missing and much opportunity for refactoring ;-)

If this is of interest to anyone else, I'll continue to build it out.

It's mostly my scratching an itch.

**Comment by mrtazz** [comment]
nice! feel free to add it to the [backends list](https://github.com/statsd/statsd/wiki/Backends) on the wiki
