### ISSUE TITLE
Counter meaning in grafana (statsd -> telegraf -> influxdb -> grafana)

### ISSUE THREAD

**Issue by thangld322** [statsd/statsd#678]
Hi,
I'm using statsd to count input events in my logs shipper app. 
Everytimes it receives an event, it increases `stat.inputEvents` by one.
Then, I use grafana to visualize this stat:
```
Data source: InfluxDB
Query: SELECT "value" FROM "stat_inputEvents" WHERE ("metric_type" = 'counter') AND $timeFilter
```

Since the graph is not always going up, so it is not counter from beginning.
So what does its value mean please? Events per second, events per ten seconds, ...?

**Comment by BlueHatbRit** [comment]
Hi @thangld322, so sorry for the delay, looks like I had notifications setup wrong. I think the [documentation](At each flush the current count is sent and reset to 0.) clears up this question for you:

> At each flush the current count is sent and reset to 0.

So it's a count per flush, if your flush interval is once a second then it'll be an account per second, if your flush interval is every 10 seconds then it'll be a count over every 10 seconds. Most standard setups will usually use per second, in this case the counter will count up over a second and then reset once it's flushed. This way you'll get a total count of events per second. If you're looking for a total count over 1 hour for instance, you can then aggregate over each second for that hour, so you should be able to then eek out metrics at whatever depth you want. Graphite is quite nice as doing this, and I think influx can do it as well, but I've not used influx very much.
