### ISSUE TITLE
Stasd for counting events per hour-- how to reset?

### ISSUE THREAD

**Issue by perroned** [statsd/statsd#680]
Hi,
I'm looking to use Statsd for metrics such as button clicks and page loads and view it in wave front.
So far it works great, but my problem is for hour over hour data my counters for buttons constantly increase. Is there a way to reset the counter for 0? 

I thought my flush interval would reset it to 0 each time but it doesn't.

How would you recommend me to keep track of events I'd like to be able to visualize over the hour? 

Thank you

**Comment by BlueHatbRit** [comment]
Hi @perroned, what is your flush interval and are you definetely using a counter? If so, the counter will be reset on every flush.

I usually have statsd setup to flush on an interval into graphite, I'll then use graphite to aggregate metrics over larger periods such as 1 hour, 1 day, 1 week, or whatever is needed.

If you're definetely using the right metric type, could you post your configurations and a sample curl call (using something like netcat as we do in the readme) so we can reproduce the issue?

**Comment by perroned** [comment]
Thank you for getting back to me so fast!

Im definitely using a counter. I am using the Java client and my server is using the Statsd plugin for Collectd to aggregate the data before sending it off to Wave front.

From what I can see I wasn't able to explicitly provide a flush interval in Collectd so I assumed it was using the default of 10 seconds.

So is it correct in saying that if you use Statsd with a flush interval of 10 seconds, if you had a count of 5 and Statsd sent it it would be reset to 0. Then 5 minutes later the count would be starting from 0 again?

That may help me isolate the issue to Collectd then

**Comment by BlueHatbRit** [comment]
> So is it correct in saying that if you use Statsd with a flush interval of 10 seconds, if you had a count of 5 and Statsd sent it it would be reset to 0. Then 5 minutes later the count would be starting from 0 again?

Yes this is correct, you can see our [documentation on it](https://github.com/statsd/statsd/blob/master/docs/metric_types.md#counting) as well:

> At each flush the current count is sent and reset to 0. If the count at flush is 0 then you can opt to send no metric at all for this counter, by setting config.deleteCounters (applies only to graphite backend). Statsd will send both the rate as well as the count at each flush.

I can't see any reason why the counter wouldn't be reset to 0, so this could be something between collectd as you suggested. However i've only used collectd in a limit capacity so we may not be the people to talk to on that one. You could use the `dumpMessages` configuration to check what messages are coming through to statsd, which will tell you what messages statsd is receiving. You can see more details of this in the [example configuration](https://github.com/statsd/statsd/blob/master/exampleConfig.js).

**Comment by BlueHatbRit** [comment]
I'm going to go ahead and close this, feel free to comment again if you need more help and I'll re-open it.

**Comment by josephwibowo** [comment]
For reference, collectd has a config in the plugin you need to do to not maintain a cumulative count.
https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_st
`DeleteCounters true`
