### ISSUE TITLE
suppress log `statsite[12503]: Failed parse metric! Input: S.None`

### ISSUE THREAD

**Issue by swbiswal** [statsd/statsd#700]
Hi There,
I want to suppress `statsite[12503]: Failed parse metric! Input: S.None` from statsite log so that It will save disk space.
We are getting this error(i.e. input as `S.None`) when we set rate less than 1 in some python statsd metrics client.
e.g.
stats_client.incr("matrics_name", rate=0.5) will bring 50% time proper matrics name push and 50% time it will push "None".
First I'd like to skip this parse metrics check, and include "None" into the parse. If is it not possible by overwrite some config, I want atleast suppress this error log. Can someone help me here?

**Comment by mheffner** [comment]
@swbiswal You probably want to file this issue over at the statsite repo: https://github.com/statsite/statsite

**Comment by swbiswal** [comment]
Opps sorry, wrong window. May be you can help me on this. Is there any way not to send at all to statsite at all in case of None. 

```
    def _prepare(self, stat, value, rate):
        if rate < 1:
            if random.random() > rate:
                return
```
Here it returns None but we want to skip push in case of None. I know I can override `_send_stat` and put a check condition, but trying to avoid our own version instead for default statsd.

**Comment by BlueHatbRit** [comment]
@swbiswal statsite is a complete re-implementation of statsd in a different language, if you need to support using the statsite software then you approach them at https://github.com/statsite/statsite as @mheffner suggested as we can't help with that.

If you're using the statsd daemon (from this repo) then it would be good if you can provide more detail on what you're trying to do, what components you're using, and what you've tried already.

**Comment by swbiswal** [comment]
Okay No problem.
