### ISSUE TITLE
Version switcher in online documentation does not work in v3.2.2 and earlier

### ISSUE THREAD

**Issue by daniel-dara** [statsd/statsd#718]
If you visit the [online documentation](https://statsd.readthedocs.io), there is a dropdown in the lower left for switching versions. If you switch to v3.2.2 or earlier, then the dropdown no longer works (clicking on it does nothing as opposed to opening the list of versions again).

The following javascript error appears in the console when switching to a version where the switcher is broken. Perhaps it is related.
```
(index):412 Uncaught ReferenceError: SphinxRtdTheme is not defined
    at HTMLDocument.<anonymous> ((index):412)
    at f (jquery-2.0.3.min.js:23)
    at Object.fireWith [as resolveWith] (jquery-2.0.3.min.js:23)
    at Function.ready (jquery-2.0.3.min.js:22)
    at HTMLDocument.dt (jquery-2.0.3.min.js:22)
```

**Comment by BlueHatbRit** [comment]
Hi @daniel-dara, I'm afraid we don't own that python module, not the docs for it. I think this is the repo you're after - https://github.com/jsocol/pystatsd/tree/master

**Comment by daniel-dara** [comment]
Ah sorry for the mix-up. Thanks for the link!
