### ISSUE TITLE
[Wiki] Link to additional Perl clients

### ISSUE THREAD

**Issue by robrwo** [statsd/statsd#720]
The wiki page at https://github.com/statsd/statsd/wiki#client-implementations is missing several Perl client implementations:
- [Net::Statsd::Lite](https://metacpan.org/pod/Net::Statsd::Lite)
- [Net::Statsd::Tiny](https://metacpan.org/pod/Net::Statsd::Tiny)
- [Net::DogStatsd](https://metacpan.org/pod/Net::Dogstatsd)
- [DataDog::Statsd](https://metacpan.org/pod/DataDog::DogStatsd)
- [Metrics::Any::Adapter::Statsd](https://metacpan.org/pod/Metrics::Any::Adapter::Statsd)
- [Net::Async::Statsd](https://metacpan.org/pod/Net::Async::Statsd)

**Comment by BlueHatbRit** [comment]
Thanks for this @robrwo, I've added these to the Perl clients section :)
