### ISSUE TITLE
Support per unit bucket boundaries

### ISSUE THREAD

**Issue by yux0** [statsd/statsd#732]
Currently, we are on Go sdk v0.30.0 and implement a customized aggregator selector to support per unit bucket boundaries. [sample](https://github.com/temporalio/temporal/blob/master/common/metrics/opentelemetry_aggregator_selector.go#L58).

I am trying to upgrade to v0.33.0 and do not find a way to matchInstrumentUnit. Is there support of per unit bucket boundaries in v0.33.0?

**Comment by BlueHatbRit** [comment]
I'm guessing this is the reason you closed the ticket, but just want to comment for anyone else who may come across this later. This repo is for the statsd daemon service, we don't maintain any sdks here, those are all created and supported by other people.

Sorry we couldn't be more help, I know nothing about Go!
