### ISSUE TITLE
Assert statsd was called in test with tags in any order

### ISSUE THREAD

**Issue by gonzaloamadio** [statsd/statsd#749]
I have a functon that is calling statsd with tags, and I want to test it. There is an `any_order` that let assert calls to statsd in any order. But when speaking about the tags list, if it is not in the same order, then it does fail.

This is the function:
```
def foo():
    # I define it like this, because I need to use this in another function
    tags = {"retry_count": 1, "req_id": 2}

    #statsd_tags = ["{}:{}".format(x, y) for x, y in tags.items()]
    statsd_tags = ["retry_count:{}".format(1), "req_id:{}".format(2)]

    statsd.incr(STATSD_PREFIX, tags=statsd_tags)
  
   some_model.add_tags(tags)
```

If I create statsd_tags with list comprehension, statsd_tags list is not on the same order. But I think usually we do not care the order of the tags list.

So in a test if I do this:
```
    @patch('my_module.statsd.incr')
    def test_foo(self, mock_statsd_incr):
        statd_calls= [
            call(STATSD_PREFIX + ".process_oct_retry_search.attempt", tags=["retry_count:1", "req_id:2"])
        ]
        mock_statsd_incr.assert_has_calls(statd_calls)
```

It is a flaky test, as the tags list does not always comes in that order. But I do not care about that order.

Imagine I have 50 tags, then I have to hardcode the order of the tags.

Is it possible to add a parameter like `tags_any_order = True`

**Comment by BlueHatbRit** [comment]
Hey @gonzaloamadio sorry for the delay - this repo is the statsd daemon itself. From what I can tell you're asking about an interfacing library, maybe for python or something? Those aren't maintained by us, you'll need to find the maintainer of the specific package you're using and raise the issue with them.
